#!/usr/bin/env python3

import re
import os
import datetime

ignore_tags = ["10", "2r"]

def process_block(block: str, links: list[str], date: datetime.datetime):
  datetime_rfc_format = date.strftime("%Y-%m-%d")
  # find all #tag in block
  tags = re.findall(r"#\w+", block)
  for t in tags:
    block = block.replace(t, "")
  tags = [t[1:] for t in tags if t[1:] not in ignore_tags]
  block = block[2:]
  block = block.strip()
  title = block.replace("|","")
  content = ""
  extra = ""
  if len(links) == 1:
    content = f"[{block}]({links[0]})"
    extra = f'[extra]\nurl="{links[0]}"\n'
  else:
    inside_link = False
    i = 0
    while i < len(block):
      if block[i] == "|":
        inside_link = not inside_link
        if not inside_link:
          content += f"]({links.pop(0)})"
        else:
          content += "["
      else:
        content += block[i]
      i += 1
  fc = (
    f'+++\n'
    f'title="{title}"\n'
    f'date={datetime_rfc_format}\n'
    f'[taxonomies]\n'
    'tags=[' + ",".join("\"" + t + "\"" for t in tags) + ']\n'
    f"{extra}"
    "+++\n"
    f"{content}"
  )
  ft = title[:30].lower().replace(" ", "-").replace("/", "-")
  with open(f"/home/tadeas/projects/tadeaspaule.github.io/content/bits/{ft}.md", "w+") as f:
    f.write(fc)



last_date = datetime.datetime(2023, 6, 10)
today = datetime.datetime.today()
daydiff = (today - last_date).days
for i in range(1, daydiff + 1):
  d = (last_date + datetime.timedelta(days=i))
  fname = d.strftime("%Y_%m_%d.md")
  path = f"/home/tadeas/Mysynced/logseq/journals/{fname}"
  if not os.path.isfile(path):
    continue
  with open(path, "r") as f:
    lines = f.readlines()
  i = 0
  while i < len(lines):
    if lines[i].find("#10") != -1:
      links = []
      j = 1
      while i + j < len(lines) and lines[i+j][0] == "\t":
        if not lines[i+j].startswith("\t- http"):
          j += 1
          continue
        links.append(lines[i+j][2:].strip())
        j += 1
      process_block(lines[i], links, d)
      i = i + j
    else:
      i += 1

