#!/bin/bash

scripts_dir="$HOME/site/helper-scripts"
$scripts_dir/delete-link-files
$scripts_dir/prepare
zola build
$scripts_dir/delete-link-files

cd public
echo 'tadeas.dev' > CNAME

git init
git add -A
git commit -m "deploy"
git push -f git@github.com:tadeaspaule/tadeaspaule.github.io.git master:gh-pages

cd -

